name: pyroid_flutter_clone
description: "Flutter ile Gelişmiş Python IDE"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chaquopy: ^11.1.1
  code_text_field: ^2.0.1
  flutter_highlight: ^0.7.0 # highlight yerine doğrudan bunu eklemek versiyonu dengeler

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
