name: pyroid_flutter_clone
description: "Flutter ile Gelişmiş Python IDE"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Git bağlantısı kaldırıldı, pub.dev üzerindeki resmi sürümler eklendi:
  chaquopy: ^11.1.1
  code_text_field: ^2.0.1
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
