name: Pyroid Ultra Builder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Bağımlılıkları Sunucuya Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi7
        sudo apt-get install -y autoconf automake libtool curl lld cmake Patch
        pip install --upgrade pip
        pip install buildozer cython==0.29.33 setuptools

    - name: APK Derlemeyi Başlat (PIP & OpenCV Dahil)
      run: yes | buildozer android debug

    - name: Hazır APK Dosyasını Yayınla
      uses: actions/upload-artifact@v4
      with:
        name: Pyroid-Ultra-Final-APK
        path: bin/*.apk
        
